### ISSUE TITLE
中文文档的锚点样式呈现有误

### ISSUE THREAD

**Issue by KimYangOfCat** [windicss/docs-cn#32]
中文文档目前的标题效果时这样的：
> # 配置 Windi CSS {#configuring-windi-css}

更详细的效果可以查看[文档](https://cn.windicss.org/guide/configuration.html#%E9%85%8D%E7%BD%AE-windi-css-configuring-windi-css)

但是 {#configuring-windi-css} 作为锚点信息，不是不应该渲染出来吗？正确的渲染效果可以参考 [webpack 中文文档](https://webpack.docschina.org/concepts/#entry) 

出现这个问题的根本原因应该是两个仓库的静态文档生成器的渲染逻辑不同导致的，本仓库的 VitePress 并不支持这样添加锚点的方法。
我想到的解决方案有两种：
1. 修改 VitePress 的渲染逻辑，支持这种添加锚点的语法。
2. 不再手动添加锚点信息并且删除以前添加的锚点信息。

**Comment by QC-L** [comment]
Fixed! #37
